name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        # see https://github.com/actions/checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Ruby
        # see https://github.com/ruby/setup-ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: '3.3.9'
          bundler-cache: false
      - name: Install Dependencies
        run: bundle install
      - name: Run the default task
        run: bundle exec rake

  rubygems_release:
    name: RubyGems Release
    if: github.repository == 'CycloneDX/cyclonedx-ruby-gem'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test
    permissions:
      contents: write
      id-token: write
    environment: release
    steps:
      - name: Checkout Code
        # see https://github.com/actions/checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Ruby
        # see https://github.com/ruby/setup-ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: ruby
          bundler-cache: false
      - name: "Push gem to RubyGems"
        uses: rubygems/release-gem@6317d8d1f7e28c24d28f6eff169ea854948bd9f7 # v1.2.0

  github_release:
    name: GitHub Release
    if: github.repository == 'CycloneDX/cyclonedx-ruby-gem'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: rubygems_release
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        # see https://github.com/actions/checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Create GitHub Release
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --verify-tag \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
