name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# see https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4.7'
          - '3.3.9'
          - '3.2.9'
# Not supported by latest bundler. These will be added back to the build matrix later.
#    They are not being dropped from support, just from CI testing for now.
#          - '3.1.7'
#          - '3.0.7'
#          - '2.7.8'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
